#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// INMP441 I2S 引脚
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_6
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_7

#ifndef USE_TFT_DISPLAY
// SSD1306 需要 I2C
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_3
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_4
#endif

#define BUILTIN_LED_GPIO        GPIO_NUM_2
#define BOOT_BUTTON_GPIO        GPIO_NUM_9

// 显示屏选择: 注释下面这行使用SSD1306 OLED，取消注释使用ST7789V2 TFT
#define USE_TFT_DISPLAY

#ifdef USE_TFT_DISPLAY
// ST7789V2 1.69" 240x280 SPI LCD
#define LCD_SCLK_PIN    GPIO_NUM_0
#define LCD_MOSI_PIN    GPIO_NUM_1
#define LCD_MISO_PIN    GPIO_NUM_NC
#define LCD_CS_PIN      GPIO_NUM_13
#define LCD_DC_PIN      GPIO_NUM_18
#define LCD_RST_PIN     GPIO_NUM_19
#define LCD_BL_PIN      GPIO_NUM_20

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  280
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 20
#else
// SSD1306 OLED 128x64
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#endif

#endif // _BOARD_CONFIG_H_
